"""cx_Freeze build: a Windows folder install, and an MSI wrapping it.

Run from the repository root with the Windows interpreter:

    python installer/setup_cxfreeze.py build_exe      # folder + exes
    python installer/setup_cxfreeze.py bdist_msi      # installer

Two executables land in the install:

    svrspec.exe       the desktop window (no console, no socket)
    svrspec-cli.exe   the same engine on the command line

The catalogue JSON is copied next to the package rather than zipped, because the
loader reads it with `Path(__file__).parent`, and a delivery tool should let the
customer open those files and check the numbers.
"""

from __future__ import annotations

import sys
from pathlib import Path

from cx_Freeze import Executable, setup

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from svrspec import __version__  # noqa: E402

ICON = ROOT / "installer" / "svrspec.ico"


def _write_iss_version() -> None:
    """Hand the package version to Inno Setup instead of letting it keep its own.

    `svrspec.iss` used to carry `#define AppVersion "..."` by hand, which is a
    third place a version lives and the one nobody remembers. It went stale at
    0.2.7 while the package moved on, so a tagged release would have produced a
    `svrspec-0.2.7-setup.exe` sitting next to a `svrspec-0.2.8-win64.msi` and
    announced itself as the older version in Add/Remove Programs. The release
    workflow checks the *tag* against `svrspec.__version__` and would not have
    caught it, because the installer script was never part of that comparison.

    Generated rather than committed, so it cannot drift: ISCC runs after this
    script in both CI and the local build, and if it is ever run without one,
    the missing include fails the compile loudly instead of shipping a lie.
    """
    (ROOT / "installer" / "version.iss").write_text(
        "; Generated by installer/setup_cxfreeze.py -- do not edit, do not commit.\n"
        f'#define AppVersion "{__version__}"\n',
        encoding="utf-8",
    )


_write_iss_version()


def _webview_js_dir() -> Path:
    """Where pywebview keeps the JavaScript it injects into the window.

    `webview.util.load_js_files` finds this with `glob(js_dir/**/*.js)` at
    runtime, reading real files off the filesystem. If those files are not in
    the build, the glob matches nothing, `api.js` never runs,
    `window.pywebview` is never created and `pywebviewready` never fires -- and
    the failure is silent: the import succeeds, the window opens, and the page
    renders. It just never fills in, because the bridge it talks through does
    not exist. A shipped release did exactly that.

    Fail the build rather than produce that installer again.
    """
    import webview

    js_dir = Path(webview.__file__).parent / "js"
    found = sorted(p.name for p in js_dir.rglob("*.js"))
    missing = {"api.js", "finish.js"} - set(found)
    if missing:
        raise SystemExit(
            f"pywebview's JS bridge is incomplete at {js_dir}: missing {sorted(missing)}. "
            f"Found {found}. Refusing to build an app whose window cannot talk to Python."
        )
    return js_dir

#: Stable across releases: Windows uses it to recognise an upgrade rather than
#: installing a second copy side by side. Never regenerate this.
UPGRADE_CODE = "{6F2A9C31-4D8B-4E5A-9C77-3B1E0A5D8F42}"

build_exe_options = {
    "packages": ["svrspec", "webview"],
    "excludes": [
        # Nothing here needs the science stack, a GUI toolkit or a test runner;
        # excluding them keeps the install small and the build honest about
        # what it actually depends on.
        "tkinter", "unittest", "pydoc_data", "pytest", "numpy", "pandas",
        "matplotlib", "PIL", "setuptools", "pip",
    ],
    "include_files": [
        (str(ROOT / "svrspec" / "catalog"), "lib/svrspec/catalog"),
        (str(ROOT / "README.md"), "README.md"),
        # pywebview's bridge is data, not code, and cx_Freeze copies modules --
        # not the .js files sitting beside them. Keeping the package unzipped
        # (below) is necessary but not sufficient: the files have to be put
        # there. See `_webview_js_dir` for why this is fatal when it is missing.
        (str(_webview_js_dir()), "lib/webview/js"),
    ],
    # Both of these must stay unzipped, and for the same reason: they read their
    # own data files off the filesystem.
    #
    #   svrspec   the catalogue loader resolves JSON with Path(__file__).parent,
    #             and a delivery tool should let the customer open those files.
    #   webview   pywebview injects its bridge by globbing webview/js/**/*.js
    #             (see webview.util.load_js_files). Inside the zip that glob
    #             matches nothing, so api.js never runs, window.pywebview is
    #             never created, `pywebviewready` never fires -- and the window
    #             renders the page but no dropdown ever fills, because the
    #             bridge the page talks through does not exist. It fails
    #             silently: the import succeeds and the window opens.
    "zip_exclude_packages": ["svrspec", "webview"],
    "include_msvcr": True,
    "optimize": 1,
}

bdist_msi_options = {
    "upgrade_code": UPGRADE_CODE,
    "add_to_path": False,
    "initial_target_dir": r"[ProgramFiles64Folder]\svrspec",
    "install_icon": str(ICON),
    "summary_data": {
        "author": "svrspec",
        "comments": "GPU 서빙 서버 스펙 산정 시뮬레이터",
        "keywords": "server sizing llm capacity planning",
    },
    "all_users": False,
}

setup(
    name="svrspec",
    version=__version__,
    description="GPU 서빙 서버 스펙 산정 시뮬레이터",
    options={"build_exe": build_exe_options, "bdist_msi": bdist_msi_options},
    executables=[
        Executable(
            str(ROOT / "installer" / "app_entry.py"),
            base="gui",                 # no console window
            target_name="svrspec.exe",
            icon=str(ICON),
            shortcut_name="svrspec",
            shortcut_dir="ProgramMenuFolder",
            copyright="Copyright (c) 2026 rokaproj",
        ),
        Executable(
            str(ROOT / "installer" / "cli_entry.py"),
            base="console",
            target_name="svrspec-cli.exe",
            icon=str(ICON),
        ),
    ],
)
